export const routes = {
  home: "/",
  login: "/login",
  dashboard: "/dashboard",
  demoPos: "/demo-pos",
  catalogProducts: "/catalog/products",
  catalogIngredients: "/catalog/ingredients",
  finance: "/finance",
  inventory: "/inventory",
  inventoryItems: "/inventory/items",
  inventoryMovements: "/inventory/movements",
  inventoryStockLevels: "/inventory/stock-levels",
  inventoryTheoreticalStock: "/inventory/theoretical-stock",
  procurementSuppliers: "/procurement/suppliers",
  procurementInvoices: "/procurement/purchase-invoices",
  masterData: "/master-data",
  imports: "/imports",
} as const;
